#!/usr/bin/env bash
# Dotfiles installation script
set -e

DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "=================================================="
echo "🚀 Installing dotfiles from: $DOTFILES_DIR"
echo "📍 Target Home: $HOME"
echo "=================================================="

# 1. Backup existing .bashrc if present and not a loader/symlink
if [ -f "$HOME/.bashrc" ] && [ ! -L "$HOME/.bashrc" ]; then
    echo "📦 Backing up existing .bashrc to .bashrc.bak"
    cp "$HOME/.bashrc" "$HOME/.bashrc.bak"
fi

# 2. Create loader in ~/.bashrc
echo "📝 Creating loader in $HOME/.bashrc ..."
cat << EOF > "$HOME/.bashrc"
# ====================================================
# AUTO-GENERATED LOADER FOR DOTFILES
# Generated by: $DOTFILES_DIR/install.sh
# Date: $(date)
# ====================================================
export DOTFILES_DIR="$DOTFILES_DIR"
if [ -f "\$DOTFILES_DIR/.bashrc" ]; then
    source "\$DOTFILES_DIR/.bashrc"
else
    echo "⚠️  Warning: \$DOTFILES_DIR/.bashrc not found!"
fi
# ====================================================
EOF
echo "✅ Created ~/.bashrc loader"

# 3. Setup Git configuration
echo "🔧 Configuring Git..."

# Copy .gitconfig.local to HOME (use local file if configured, otherwise fall back to template)
if [ -f "$DOTFILES_DIR/.gitconfig.local" ]; then
    cp "$DOTFILES_DIR/.gitconfig.local" "$HOME/.gitconfig.local"
    echo "✅ Copied .gitconfig.local to $HOME/.gitconfig.local"
elif [ -f "$DOTFILES_DIR/.gitconfig.local.template" ]; then
    cp "$DOTFILES_DIR/.gitconfig.local.template" "$HOME/.gitconfig.local"
    echo "⚠️  .gitconfig.local not found in repo. Copied from template instead."
fi

# Link main global gitconfig
git config --global include.path "$DOTFILES_DIR/.gitconfig"
echo "✅ Git configured to include $DOTFILES_DIR/.gitconfig"

# 4. Copy .bashrc.local to HOME
if [ -f "$DOTFILES_DIR/.bashrc.local" ]; then
    cp "$DOTFILES_DIR/.bashrc.local" "$HOME/.bashrc.local"
    echo "✅ Copied .bashrc.local to $HOME/.bashrc.local"
elif [ -f "$DOTFILES_DIR/.bashrc.local.template" ]; then
    cp "$DOTFILES_DIR/.bashrc.local.template" "$HOME/.bashrc.local"
    echo "⚠️  .bashrc.local not found in repo. Copied from template instead."
fi

# 5. Install / Update GitReview dotnet tool
echo "🔍 Checking for .NET CLI & GitReview tool..."
if command -v dotnet >/dev/null 2>&1; then
    if dotnet tool list -g | grep -q "wieseknows.gitreview"; then
        echo "🔄 Updating wieseknows.GitReview tool..."
        dotnet tool update -g wieseknows.GitReview || echo "⚠️ Failed to update GitReview tool"
    else
        echo "📦 Installing wieseknows.GitReview tool..."
        dotnet tool install -g wieseknows.GitReview || echo "⚠️ Failed to install GitReview tool"
    fi
else
    echo "⚠️ .NET SDK (dotnet) not found in PATH. Skipping GitReview installation."
fi

echo ""
echo "=================================================="
echo "✅ Dotfiles installation complete!"
echo "=================================================="
echo "📌 Restart your terminal or run: source ~/.bashrc"
echo "=================================================="